### PR TITLE
Fix iOS 9 and above support

### PR DESCRIPTION
**Pull request by ocReaper**
refs  #64

### CODE REVIEW

**Comment by NiklasMerz** [comment]
@ajnrajeev Again I am asking got your review. You made the last improvements for iOS and know this topic very well. I would like to hear your opinion about this PR. Thank you very much for your work on this project.

**Comment by elsesiy** [comment]
@ocReaper Why do you duplicate the code? It's easier to create a `lazy var` and do the check once. You can entirely remove the availability checks from the two functions then..

**Comment by ocReaper** [comment]
@elsesiy I've never used or seen swift code before, therefore I have no knowledge about swift specific implementations like the `lazy var`. Nothing more, nothing less.

**Comment by elsesiy** [comment]
@ocReaper I didn't mean to offend or anything, it makes total sense if you've never done it. I can fork your branch and apply the changes if you want me to?

**Comment by ocReaper** [comment]
No problem @elsesiy! I wasn't offended. Feel free to improve the code! I will use it in production, so the cleaner the code is the better! 😉

**Comment by NiklasMerz** [comment]
Thank you both for improving this. I appreciate help from more experienced Swift developers very much.

**Comment by maitscha** [comment]
When will this one be merged?

**Comment by elsesiy** [comment]
@maitscha I added some commits to the PR in the fork and @ocReaper wanted to test them yesterday. So anytime soon I guess :)

**Comment by elsesiy** [comment]
@maitscha See [here](https://github.com/ocReaper/cordova-plugin-fingerprint-aio/pull/1)

**Comment by eduardo-santos** [comment]
@elsesiy  i tried to update my Fingerprint.swift with yours and still no success testing on iphone 6s version 11.1. Any idea?

**Comment by NiklasMerz** [comment]
@eduardo-santos Does the latest version from NPM not work for you? I have used it on an iPhone 6s Plus with iOS 11.1 without any problems.

**Comment by elsesiy** [comment]
@eduardo-santos I tested it on a 6s with 11.1 as well in a separate App which worked perfectly fine. Maybe you can share a sample project?

**Comment by eduardo-santos** [comment]
@elsesiy / @NiklasMerz i'm using this function to check the fingerprint availability: 

`async isFingerPrintAvailable(){
    try{
      const isAvailable = await this.fingerprint.isAvailable();
      console.log("Fingerprint is available: " + isAvailable);

      return isAvailable === "OK";
    }
    catch(e){
      console.error(e);
    }
    return false;
  }`

**Comment by NiklasMerz** [comment]
@eduardo-santos Are you using ionic native? What is exactly the error?

**Comment by elsesiy** [comment]
@NiklasMerz The PR has been updated with my changes, can you merge it now? :)

**Comment by NiklasMerz** [comment]
I will check that soon.

**Comment by eduardo-santos** [comment]
@NiklasMerz / @elsesiy  sorry for my delay answering. I'm using ionic native, my problem was not with the plugin, but with my own code structure. I forgot to check 'platform.ready()' again on my controller constructor before call fingerprint availability. For some reason on android it was running correctly and ios wasn't. Now i've tested on iphone 6s with ios 11.1 and it's working properly. Thank you.

**Comment by maitscha** [comment]
I have tested the latest changes on iOS 10.3.3 and iOS 11.1, works as expected.

**Comment by elsesiy** [comment]
@NiklasMerz Are we good to go here? I‘ll add some more improvements soon.

**Comment by NiklasMerz** [comment]
This pull request is quite difficult to review because the indentation was changed and the git diff is not really usfull anymore. It could help if you would avoid that. @ocReaper and @elsesiy Could you please provide test cases where the old implementation failed. The current release works for me great on iOS 10 and 11 and I never experienced problems so I need your help to test this.

I thank you very much for testing and improving this. Before changing the indenting the code looked cleaner and easier. When I find some time to test this and get your feedback I can merge this.

**Comment by elsesiy** [comment]
@NiklasMerz The file wasn't formatted correctly as per Xcode file indention rules, that's why I updated it accordingly. The old implementation didn't provide proper passcode-fallbacks provided since iOS 9 (that's what the new deviceOwnerAuthentication-policy is for). See [this SO post](https://stackoverflow.com/questions/25397184/touchid-forward-to-system-passcode-authentication) for reference. I can try to come up with a proper test case but as you said the current implementation also works on iOS 8+ and hasn't been deprecated so this PR is rather an improvement.

**Comment by NiklasMerz** [comment]
Thanks for explaining this further. I will check this.

I created a new issue for fixing the indentation #74. You should avoid indenting the whole file for a Pull request since now you can't see the changes easily.

**Comment by NiklasMerz** [comment]
This pr has been merged. Please tests your changes in Master and I will prepare a new release on npm.

**Pull request merged**
