### PR TITLE
Dutch Translation added

### PR DESCRIPTION
**Pull request by shivalipawar**
Added values-nl folder under resources and updated its reference in plugin.xml

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Could you please squash your commits to a single commit?

**Comment by shivalipawar** [comment]
Ahhw!! Currently i'm not in office so could you just squash and merge at your end that would be helpful.

**Comment by NiklasMerz** [comment]
Ok thanks. I will merge this tonight.

**Comment by shivalipawar** [comment]
Thank you!!!

**Comment by NiklasMerz** [comment]
Done. Github even does the sqaush and merge :-)

**Comment by shivalipawar** [comment]
Ohh thank you for letting me know i wasn't aware about it!!!

**Comment by NiklasMerz** [comment]
I did this the first time, too.

**Comment by shivalipawar** [comment]
Could you please update plugin version as when i get latest commit using SHA, version i get is 1.3.3 and not latest one.

**Comment by shivalipawar** [comment]
ok thanks!!

**Pull request merged**
