### PR TITLE
add optional 'allowBackup' parameter to isAvailable() #175

### LINKED ISSUE #175: iOS: no way to check if fingerprint authentication with passcode fallback is available
In iOS implementation, logic for checking authentication capabilities differs. 

In `isAvailable` plugin API method, the policy being checked with `canEvaluatePolicy` is `.deviceOwnerAuthenticationWithBiometrics`, which means biometric auth only with no fallback to passcode check. But, the `authenticate` plugin method takes as parameter `disableBackup`, which determines which policy to evaluate - with or without fallback, and default value is `.deviceOwnerAuthentication` which means to use password auth fallback and differs from behavior of `isAvailable` API. 

To make this behavior equal, `isAvailable` should also take some parameter to specify which policy to check.

### PR DESCRIPTION
**Pull request by dmitry-salnikov**
# Description

This PR closes #175 

# How did you test your changes?

1. Checked that `isAvailable({ allowBackup: true })` works correctly with passcode only enabled on device (e.g. when all touchID/faceID identities removed from device settings).
2. Checked that `isAvailable()` called without params behaves the same as before so no breaking changes were made.

### CODE REVIEW

**Comment by khaledosman** [comment]
it seems like the build is failing due to no es6 support, can you update it to use var instead? would be nice to have this merged if possible

**Comment by NiklasMerz** [comment]
Unfortunately I cannot push to the branch but thank you for the changes.

**Comment by NiklasMerz** [comment]
Sorry for pushing to your master. I suggest creating branches for PRs.

**Comment by dmitry-salnikov** [comment]
Sorry for the delay. @NiklasMerz absolutely no problem, thank you for taking care of merging this code!

**Pull request merged**
