### PR TITLE
adjust edit-config attributes so they work

### PR DESCRIPTION
**Pull request by brad**
Hi @NiklasMerz, the Android permissions weren't working for me (using cordova-android ~6). Adjusting to this fixes it.

see #87

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Hi @brad Thank you for submitting this. In the current version on npm 1.3.4 the code is simmilar to your PR. But currently I am slowly working towards making this plugin compatible to the recent versions. But I have trouble with newer versions of cordova, too.

This [blog](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) post describes the changed of cordova android 7.0.

I appreciate any further feedback.

**Comment by brad** [comment]
@NiklasMerz I see, I guess you need the `target="/manifest/uses-permission"` change at least. In my testing using `/manifet/application` added the uses-permission info as an attribute to the `<application ...` element.

**Comment by NiklasMerz** [comment]
@brad I think you are right. 

Would you like to change your PR?

**Comment by brad** [comment]
@NiklasMerz Sure, I'll update it

**Comment by brad** [comment]
@NiklasMerz Are you fixing the CI build?

**Comment by NiklasMerz** [comment]
@brad I am trying to but I do not really understand why it won´t work. Can you help me? You can reach me via [gitter](https://gitter.im/cordova-plugin-fingerprint-aio)

**Comment by brad** [comment]
@NiklasMerz I'll let you know when I've had a chance to give it a try, I think you can close this issue though

**Pull request closed without merging**
