### PR TITLE
Support Cordova-android 7.0 and fix fingerprint permission in 6.x

### PR DESCRIPTION
**Pull request by Liam-Ryan**
Fix for Issue #92

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Thanks for the PR. I will check this later today. This is a difficult problem because of the breaking changes. See #89. I would like to support oder cordova versions too

**Comment by Liam-Ryan** [comment]
Ah I see now, thank you for explaining. You'd think cordova would include some form of special comment to use different tags in xml files depending on version after a breaking change like this .

I'm still on 6.3 so that's what my fix was tested against, the sample for Android shows config-file rather than edit-config, maybe that's a solution? 
```
<config-file target="AndroidManifest.xml" parent="/*">
    <uses-permission android:name="android.permission.READ_CONTACTS" />
</config-file>
```

I'll see if I can come up with anything that works for pre and post 7, for now my project is happy to work from my fork.

**Comment by Liam-Ryan** [comment]
I spent a few hours trying to get cordova-android 7 to run with basic ionic project ( ionic start new blank ) and it's just too broken right now, all of the ionic cordova plugins had problems with the path.

Example -  Failed to install 'cordova-plugin-splashscreen': Error: ENOENT: no such file or directory, open 'E:\Development\Angular2\Cordova7\cordova7\platforms\android\AndroidManifest.xml'

I'm on latest cordova and ionic so not much I can do to test 7 further tonight, I'll have a look at doing a simple cordova only test tomorrow but it could take me a while

**Comment by NiklasMerz** [comment]
@Liam-Ryan You got to the same conclusion as @brad and myself a few weeks ago. I don´t really know to to handle this well.

**Comment by Liam-Ryan** [comment]
@NiklasMerz This app is working for me with cordova-android 7 (latest ionic and cordova ) 

https://github.com/Liam-Ryan/ionic-cordova-android-7

Adding fingerprint-aio after following build instructions causes the problems above but it no longer references the ionic applications it just shows the error. I'll continue working on the problem but thought this repo be useful to you

**Comment by NiklasMerz** [comment]
Thank you very much for your help. I dont have a working android 7 build enviroment. If you find an elegant solution I will check this out.

**Comment by Liam-Ryan** [comment]
No problem, right now I've tracked down the problem for this error message - it's the  tags that copy the png icons. If I comment them out or replace with icon tags then the plugin installs successfully but I get an error when running the emulator as the icons haven't been copied to where they are expected. 

I've altered a few cordova plugins but I haven't created one from scratch so it could take me a while to figure out how to fix this in a backward compatible way, would you have any suggestions? 

Here's the offending tags - 

```
    <source-file src="res/android/drawable/ic_fingerprint_success.xml" target-dir="res/drawable"/>
    <source-file src="res/android/drawable-hdpi/ic_fp_40px.png" target-dir="res/drawable-hdpi"/>
    <source-file src="res/android/drawable-mdpi/ic_fp_40px.png" target-dir="res/drawable-mdpi"/>
    <source-file src="res/android/drawable-nodpi/android_robot.png" target-dir="res/drawable-nodpi"/>
    <source-file src="res/android/drawable-xhdpi/ic_fp_40px.png" target-dir="res/drawable-xhdpi"/>
    <source-file src="res/android/drawable-xxhdpi/ic_fp_40px.png" target-dir="res/drawable-xxhdpi"/>
    <source-file src="res/android/drawable-xxxhdpi/ic_fp_40px.png" target-dir="res/drawable-xxxhdpi"/>
```

**Comment by Liam-Ryan** [comment]
The good news is I've tested this and it's working in both cordova 6.3.0 and 7!

The bad news is I clobbered the formatting  with tabs and messed up the commits on the pr branch with all of my messing around :$ I'll push another commit now with spaces.

By the way if you have an old plugin installed you'll need to delete the plugins/cordova-plugin-fingerprint-aio to see the fix work, otherwise it keeps the old layout which triggers the problems in cordova 7

**Comment by Liam-Ryan** [comment]
Ok formatting fixed, sorry about that. 

To summarize my understanding - From 7.0 you can no longer use source-file for pngs. Whatever way it happens it seems to put it into legacy mode, meaning any plugins after the one with the pngs will fail since they look for their files in the old locations

The fix was to switch to resource-files, however this still appeared broken when testing. I had to delete my plugins/cordova-plugin-fingerprint-aio and remove the platform to see everything working. 

I also changed edit-config to config-file since this will search for the manifest using wildcards and means that the permission is set correctly in the manifest for both 6.3 and 7.0. I've tested both versions on emulators by checking isAvailable(), calling the check and verifying a fingerprint

**Comment by NiklasMerz** [comment]
That sounds wonderful. I need to do some tests but this looks like you did it :+1: . Thanks for your work and explaining the issue very well.

**Comment by LKDevelopment** [comment]
Hello guys,

i run into the same problem and it breaks currently a production app. Since, i know that the fix would take some more time, what is your suggested hotfix @NiklasMerz ?

**Comment by Liam-Ryan** [comment]
@LKDevelopment You can try running off of this pr branch, it would also help with testing. Be sure to delete your old plugin folder and remove platform.

**Comment by NiklasMerz** [comment]
@LKDevelopment Yes like @Liam-Ryan said try his branch. This would be usefull for testing this PR, too.
I would love to hear your feedback.

**Comment by LKDevelopment** [comment]
Yeah i've updated to this branch. 

First feedback:
Build runs as good as ever
APK is ~1 MB bigger than before (before 9,7 MB, now 10,6 MB)
First Tests on Android 8.1 looks really good, like before.  I'll push it out to production and will check again than.

**Comment by LKDevelopment** [comment]
First Monitoring Results after update:
Android 8.1
3 Devices (+ 2 from myself)
0 Crashes

Android 8.0
3 Devices (+ 1 from myself)
0 Crashes

Android 7.1
5 Devices
0 Crashes

Android 7.0
2 Devices
0 Crashes

So looks like it works :)

**Comment by NiklasMerz** [comment]
@LKDevelopment Thanks for your update

**Comment by LKDevelopment** [comment]
After two days in production now ~80% devices has the update. I can't see any error or failure anymore.

**Comment by NiklasMerz** [comment]
@LKDevelopment Thanks for your testing. This convices me to merge that finally :).

**Comment by NiklasMerz** [comment]
I started doing an RC tag on NPM for testing. 

```
cordova plugin add cordova-plugin-fingerprint-aio@rc
```

@brad @Liam-Ryan Please let me know if your tests were successful.

**Comment by brad** [comment]
@NiklasMerz It's working great for me on Android. I'll check later today to make sure it works on iOS as well

**Comment by LKDevelopment** [comment]
@NiklasMerz i've pulled in the RC and released it als Beta in Android and Testflight Build. The metrics looks good :) can't see any error.

**Comment by NiklasMerz** [comment]
Thank you everybody. I have published this as the new release.

**Pull request merged**
