### PR TITLE
Make isAvailable return more information (api-breaking change)

### LINKED ISSUE #166: We would like to get more information in the error callback for isAvailable
### Feature Request

Currently isAvailable returns "Not Available" for every error scenario, regardless of whether this is due to biometry being not available, or the user has denied permissions, etc. 

We would like to get an object in the callback instead of a string, but we don't want to break the current isAvailable().

#### Feature Description

The Object should contain the error code, this could be an integer (-6, -4, etc), or string description, or any way to distinguish the different kinds of errors.

for iOS e.g.:
* user has denied biometric permissions 
* biometry not enrolled
* biometry not available

for android...
* would be undefined since android doesn't return any codes.

We currently have code which changes the parameter type from string to object, but we realize this is not ideal.

We considered making a new method so that isAvailable(success, (string) => ...) works as normal, we could call it verifyBiometric(success, (object) => ... )

What do you think? We can make a pull request and implement however you like.

Thanks for your help.

### PR DESCRIPTION
**Pull request by byronaltice**
# Description
Changes the return of isAvailable from a string to a json object to display different types of errors

# How did you test your changes?
https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/166

Closes #166

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Closing this in favor pf #171. @byronaltice Are you ok with that?

**Comment by NiklasMerz** [comment]
Who did which tests on this PR?

cc @byronaltice @greaterking

**Comment by NiklasMerz** [comment]
@byronaltice Could you please allow me to push to this PR or change the errors in tests.js to JSON.stringify yourself. That should be done in this PR.

See https://github.com/byronaltice/cordova-plugin-fingerprint-aio/pull/1

**Comment by byronaltice** [comment]
@NiklasMerz Sorry for the delay, I merged your changes.

**Comment by byronaltice** [comment]
Additional Info, manually tested on android and ios devices, and emulators.

**Comment by NiklasMerz** [comment]
LGTM. Thank you very much.

**Comment by NiklasMerz** [comment]
Released in v2 please test and thanks for your contribution

https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/releases/tag/v2.0.0

**Pull request merged**
