### PR TITLE
#151: Attempt to invoke virtual method 'boolean android.hardware.fing…

### PR DESCRIPTION
**Pull request by emelnychenko**
…erprint.FingerprintManager.isHardwareDetected()' on a null object reference

- Added null check at every place where mFingerPrintManager used to prevent "boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference"

# Description

Hey guys. Yesterday I testing my app on Xiaomi Redmi 6A and met next exception:

`
E/PluginManager: Uncaught exception from pluginjava.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object referenceat de.niklasmerz.cordova.fingerprint.Fingerprint.execute(Fingerprint.java:256)at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)at org.apache.cordova.PluginManager.exec(PluginManager.java:132)at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)at android.os.MessageQueue.nativePollOnce(Native Method)at android.os.MessageQueue.next(MessageQueue.java:331)at android.os.Looper.loop(Looper.java:149)at android.os.HandlerThread.run(HandlerThread.java:65)
`

Currently, I want to use your plugin in next release of my app but it's unstable on some devices. Please review PR and bump new patch. Many thanks.

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Thank you for your contribution. This might be a patch but since #179 is planned for a new major release I am not sure if I am doing a patch release. #179 replaces the complete Android implementation.

**Comment by emelnychenko** [comment]
Hey @NiklasMerz. Thanks for your response. Do you know when #179 will be ready to release?

**Comment by NiklasMerz** [comment]
@emelnychenko I am on it. Did you test #179 yourself. It should be quite good.

**Comment by richardshergold** [comment]
I'm having this issue now (on an Android 9 device).  Do you know when this will be fixed?

**Comment by NiklasMerz** [comment]
Closed since #179 fixed this issue. Thank you for contributing!

**Pull request closed without merging**
