### PR TITLE
Switch to android x

### PR DESCRIPTION
**Pull request by maximedasilva**
Switch this plugin to androidX and use biometric from  androidx.biometric.BiometricManager

### CODE REVIEW

**Comment by NiklasMerz** [comment]
@exxbrain You are the expert. But should we wait for the cordova-android version which should come soon and support AndroidX?

**Comment by exxbrain** [comment]
> @exxbrain You are the expert. But should we wait for the cordova-android version which should come soon and support AndroidX?

@NiklasMerz, no I don't think it is necessary to wait. If it is needed you can support 4 and 3 versions separately.

**Comment by rhuffy** [comment]
Will this be merged soon? The deprecated imports in `BiometricActivity.java` are causing build failures for me.

**Comment by NiklasMerz** [comment]
> 
> 
> There some deprecated com.android.support libraries still exist in the project. Why not to migrate to androidx completely?

@maximedasilva Would you like to take this up? Any ideas.

**Comment by NiklasMerz** [comment]
Nevermind. I removed the dependencies and at least the CI build was successful

**Comment by rhuffy** [comment]
for anyone still waiting on this release, here's a fix [https://github.com/mikehardy/jetifier](https://github.com/mikehardy/jetifier)

**Comment by NiklasMerz** [comment]
I started preparing a release just yesterday. Master branch should use AndroidX without problems. I appreciate any feedback. 
GitHub <notifications@github.com> wrote:
“for anyone still waiting on this release, here's a fix https://github.com/mikehardy/jetifier”

**Comment by mburger81** [comment]
@NiklasMerz can you please release this?
Not sure why, but jetifier seems to not work as expected if I build app in docker

**Pull request merged**
